services:
  mariadb:
    image: mariadb:11
    container_name: ropa_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ropa_db
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
  app:
    build: .
    container_name: ropa-app
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/ropa_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  frontend:
    build: ./frontend
    container_name: ropa-frontend
    restart: always
    ports:
      - "8081:80"
volumes:
  mariadb_data: